lstest: fix/improve process of -d option; fix indent;

diff --git a/bkr-runtest/lstest b/bkr-runtest/lstest
--- a/bkr-runtest/lstest
+++ b/bkr-runtest/lstest
@@ -25,153 +25,198 @@ parse_yaml() {
 	}
 	END {print gensub("^ ", "", 1, s)}'
 }
+
+distroMatch() {
+	condition=$1
+	distro=$2
+	[[ -z "$distro" ]] && return 0
+
+	case $distro in
+		RHEL-5*) family=el5;;
+		RHEL-6*) family=el6;;
+		RHEL-7*) family=el7;;
+		Fedora*) family=el7;;
+		*)	family=;;
+	esac
+	[[ -z "$family" ]] && return 0
+
+
+	nodistrof=$(eval set -- $condition; for c; do [[ "$c" =~ ^nodistro= ]] && echo -n "${c#*nodistro=}"; done)
+	distrof=$(eval set -- $condition; for c; do [[ "$c" =~ ^distro= ]] && echo -n "${c#*distro=}"; done)
+	[[ -z "$distrof" && -z "$nodistrof" ]] && return 0
+
+	#white list
+	if [[ -n "$distrof" ]]; then
+		if [[ "$distrof" =~ $family ]]; then
+			return 0
+		else
+			return 1
+		fi
+	fi
+
+	#black list
+	if [[ -n "$nodistrof" && "$nodistrof" =~ $family ]]; then
+		return 1
+	fi
+
+	return 0
+}
+
 _caseInfo() {
-    [ $# -lt 1 ] && {
-        echo "Usage: func <case path>" >&2
-        return 1
-    }
-    local casepath=$1 pkgName= type= level=
-    local info= name= topo=singleHost ssched=no f=runtest.sh pkgName
-    [ -d "$casepath" ] || { echo "{warn} dir [$casepath] not exist."; }
+	[ $# -lt 1 ] && {
+		echo "Usage: func <case path>" >&2
+		return 1
+	}
+	local casepath=$1 pkgName= type= level=
+	local info= name= topo=singleHost ssched=no f=runtest.sh pkgName
+	[ -d "$casepath" ] || { echo "{warn} dir [$casepath] not exist."; }
 
-    pushd $casepath >/dev/null;
-        unlink testinfo.desc 2>/dev/null
-        make testinfo.desc &>/dev/null
-        [ -f testinfo.desc ] || {
-            echo "{ERROR} [$casepath/] make testinfo.desc fail, please fix the Makefile." >&2
-            popd >/dev/null; return 1
-        }
+	pushd $casepath >/dev/null;
 
-        #get case name and time
-        name=$(awk -F'[: =\t]+' '/^Name:/{print $2}' testinfo.desc)
-        [ -z "$name" ] && {
-            echo "{ERROR} [$casepath/] casename NULL, maybe Makefile wrong." >&2
-            popd >/dev/null; return 1
-        }
-        time=$(awk -F'[: =\t]+' '/^TestTime:/{print $2}' testinfo.desc)
-        echo $time | egrep -q '[0-9]+h' && time=$((${time/h/}*60))m
-        echo $time | egrep -q '[0-9]+d' && time=$((${time/d/}*24*60))m
+	unlink testinfo.desc 2>/dev/null
+	make testinfo.desc &>/dev/null
+	[ -f testinfo.desc ] || {
+		echo "{ERROR} [$casepath/] make testinfo.desc fail, please fix the Makefile." >&2
+		popd >/dev/null; return 1
+	}
 
-        #get pkg name
-        unset PACKAGE_NAME PACKAGE
-        eval "$(egrep '^[[:space:]]*(export *)?PACKAGE(_NAME)?=[^ #]' -h * .* 2>/dev/null|sed 's;export;;')"
-        pkgName=${PACKAGE_NAME}
-        test -z "${pkgName}" && pkgName=${PACKAGE}
-        test -z "${pkgName}" && pkgName=?
+	#get case name and time
+	name=$(awk -F'[: =\t]+' '/^Name:/{print $2}' testinfo.desc)
+	[ -z "$name" ] && {
+		echo "{ERROR} [$casepath/] casename NULL, maybe Makefile wrong." >&2
+		popd >/dev/null; return 1
+	}
+	time=$(awk -F'[: =\t]+' '/^TestTime:/{print $2}' testinfo.desc)
+	echo $time | egrep -q '[0-9]+h' && time=$((${time/h/}*60))m
+	echo $time | egrep -q '[0-9]+d' && time=$((${time/d/}*24*60))m
 
-        #sepatate scheduling?
-        egrep -q -i ' *DANGEROU?S=yes' -r . && ssched="yes.dangerous"
-        egrep -q -i ' *STRESS=yes' -r . && ssched="yes.stress"
+	#get pkg name
+	unset PACKAGE_NAME PACKAGE
+	eval "$(egrep '^[[:space:]]*(export *)?PACKAGE(_NAME)?=[^ #]' -h * .* 2>/dev/null|sed 's;export;;')"
+	pkgName=${PACKAGE_NAME}
+	test -z "${pkgName}" && pkgName=${PACKAGE}
+	test -z "${pkgName}" && pkgName=?
 
-        # if cost so many time separate schedule too
-        echo $maxtime | egrep -q '[0-9]+h' && maxtime=$((${maxtime/h/}*60))
-        echo $maxtime | egrep -q '[0-9]+d' && maxtime=$((${maxtime/d/}*24*60))
-        maxtime=${maxtime//[^0-9]/}
-        [ "$ssched" = "no" -a "${time/m/}" -gt "${maxtime:-120}" ] && ssched="yes.longtime"
+	#sepatate scheduling?
+	egrep -q -i ' *DANGEROU?S=yes' -r . && ssched="yes.dangerous"
+	egrep -q -i ' *STRESS=yes' -r . && ssched="yes.stress"
 
-        #get topologic if is multihost
-        grep -q "Type:[[:space:]]*Multihost" testinfo.desc &&
-            topo=multiHost.1.1
-        grep -q '\${\?CLIENTS}\?' $f && grep -q '\${\?SERVERS}\?' $f &&
-            topo=multiHost.1.1
-        ##if specify the machine acount in testinfo.desc
-        nums=$(grep -i "Type:[[:space:]]*Multihost" testinfo.desc | grep -o '[0-9]\+')
-        read ServerNeed ClientNeed <<<$nums
-        test -n "$ServerNeed" -o -n "$ClientNeed" &&
-            topo=multiHost.${ServerNeed:-1}.${ClientNeed:-1}
-        ##if specify the machine acount in runtest.sh
-        egrep -q '^[[:space:]]*(Client|Server)Need=' $f && {
-            eval "$(egrep '^[[:space:]]*(Client|Server)Need=' $f)"
-            topo=multiHost.${ServerNeed:-1}.${ClientNeed:-1}
-        }
+	# if cost so many time separate schedule too
+	echo $maxtime | egrep -q '[0-9]+h' && maxtime=$((${maxtime/h/}*60))
+	echo $maxtime | egrep -q '[0-9]+d' && maxtime=$((${maxtime/d/}*24*60))
+	maxtime=${maxtime//[^0-9]/}
+	[ "$ssched" = "no" -a "${time/m/}" -gt "${maxtime:-120}" ] && ssched="yes.longtime"
 
-        #get type info
-        type=$(awk '{match($0,"Type:[ \t]*.*(.egression|.tress|.unction|.anity)",M); if(M[1]) print M[1]}' testinfo.desc)
-        read type nil <<<${type}
+	#get topologic if is multihost
+	grep -q "Type:[[:space:]]*Multihost" testinfo.desc &&
+	topo=multiHost.1.1
+	grep -q '\${\?CLIENTS}\?' $f && grep -q '\${\?SERVERS}\?' $f &&
+	topo=multiHost.1.1
+	##if specify the machine acount in testinfo.desc
+	nums=$(grep -i "Type:[[:space:]]*Multihost" testinfo.desc | grep -o '[0-9]\+')
+	read ServerNeed ClientNeed <<<$nums
+	test -n "$ServerNeed" -o -n "$ClientNeed" &&
+	topo=multiHost.${ServerNeed:-1}.${ClientNeed:-1}
+	##if specify the machine acount in runtest.sh
+	egrep -q '^[[:space:]]*(Client|Server)Need=' $f && {
+		eval "$(egrep '^[[:space:]]*(Client|Server)Need=' $f)"
+		topo=multiHost.${ServerNeed:-1}.${ClientNeed:-1}
+	}
 
-        #get test level info
-        level=$(awk '{match($0,"(Type):[ \t]*.*([Tt]ier[0-9]+)",M); if(M[2]) print M[2]}' testinfo.desc)
-        level=${level:-Tier1}
-        read level nil <<<${level}
-        rm -rf testinfo.desc
+	#get type info
+	type=$(awk '{match($0,"Type:[ \t]*.*(.egression|.tress|.unction|.anity)",M); if(M[1]) print M[1]}' testinfo.desc)
+	read type nil <<<${type}
 
-        pAttrs="pkg=${pkgName:--} topo=$topo time=$time ssched=$ssched type=$type level=$level"
+	#get test level info
+	level=$(awk '{match($0,"(Type):[ \t]*.*([Tt]ier[0-9]+)",M); if(M[2]) print M[2]}' testinfo.desc)
+	level=${level:-Tier1}
+	read level nil <<<${level}
+	rm -rf testinfo.desc
+
+	pAttrs="pkg=${pkgName:--} topo=$topo time=$time ssched=$ssched type=$type level=$level"
 
 	subtests_generator="gen_subtest.sh"
 	[ -x $subtests_generator ] && sh $subtests_generator
-        subtests=$(egrep -h '^[[:space:]]*(Attr|Param|GlobalSetup):' subtest.desc subtest.list  2>/dev/null)
-        if [ "$FORMAT" = raw -o -z "$subtests" ]; then
-            testinfo="$name Attr: ${pAttrs% }"
-            [ "$FORMAT" = pol ] && testinfo="fs-qe case:$name tag:$pkgName,$level,$type"
-            echo "$testinfo"
-        else
-            while read l; do
-                #get the attr list
-                attrs=$(parse_yaml "$l"|sed -n '/^Attr: */{s///;p;q}')
-                echo "$attrs"|grep -q "ssched=" && {
-			pAttrs=$(eval $attrs; echo "$pAttrs"|sed -r "s/(ssched=)[^ ]*/\1$ssched/")
-			attrs=$(echo "$attrs"|sed 's/\<ssched=[^ ]* *//')
-		}
-                echo "$attrs"|grep -q "level=" && {
-			pAttrs=$(eval $attrs; echo "$pAttrs"|sed -r "s/(level=)[^ ]*/\1$level/")
-			attrs=$(echo "$attrs"|sed 's/\<level=[^ ]* *//')
-		}
-                echo "$attrs"|grep -q "type=" && {
-			pAttrs=$(eval $attrs; echo "$pAttrs"|sed -r "s/(type=)[^ ]*/\1$type/")
-			attrs=$(echo "$attrs"|sed 's/\<type=[^ ]* *//')
-		}
-                attrs="$pAttrs $attrs"
-                testinfo="$name Attr: ${attrs% }"
+	subtests=$(egrep -h '^[[:space:]]*(Attr|Param|GlobalSetup):' subtest.desc subtest.list  2>/dev/null)
+	if [ "$FORMAT" = raw -o -z "$subtests" ]; then
+		testinfo="$name Attr: ${pAttrs% }"
+		[ "$FORMAT" = pol ] && testinfo="fs-qe case:$name tag:$pkgName,$level,$type"
+		echo "$testinfo"
+	else
+		while read l; do
+			#get the condition config
+			condition=$(parse_yaml "$l"|sed -n '/^Condition: */{s///;p;q}')
+			[ -n "$condition" ] && {
+				if [ -n "$distro" ]; then
+					distroMatch "$condition" $distro || continue
+				fi
+				testinfo+=", Condition: $condition"
+			}
 
-                #get the params list
-                args=$(parse_yaml "$l"|sed -n '/^Param: */{s///;p;q}')
-                [ -n "$args" ] && testinfo+=", Param: $args"
+			#get the attr list
+			attrs=$(parse_yaml "$l"|sed -n '/^Attr: */{s///;p;q}')
+			echo "$attrs"|grep -q "ssched=" && {
+				pAttrs=$(eval $attrs; echo "$pAttrs"|sed -r "s/(ssched=)[^ ]*/\1$ssched/")
+				attrs=$(echo "$attrs"|sed 's/\<ssched=[^ ]* *//')
+			}
+			echo "$attrs"|grep -q "level=" && {
+				pAttrs=$(eval $attrs; echo "$pAttrs"|sed -r "s/(level=)[^ ]*/\1$level/")
+				attrs=$(echo "$attrs"|sed 's/\<level=[^ ]* *//')
+			}
+			echo "$attrs"|grep -q "type=" && {
+				pAttrs=$(eval $attrs; echo "$pAttrs"|sed -r "s/(type=)[^ ]*/\1$type/")
+				attrs=$(echo "$attrs"|sed 's/\<type=[^ ]* *//')
+			}
+			attrs="$pAttrs $attrs"
+			testinfo="$name Attr: ${attrs% }"
 
-                #get the global config
-                conf=$(parse_yaml "$l"|sed -n '/^GlobalSetup: */{s///;p;q}')
-                sconf=$(eval set -- $conf; for ((i=1;i<=$#;i++)); do echo "${!i}"; done|sort)
-                sconf=$(echo "$sconf"| while read c; do echo -n "$c"|sed -e "s;';'\"'\"';g" -e "s/^/'/" -e "s/$/' /"; done)
-                [ -n "$sconf" ] && testinfo+=", GlobalSetup: $sconf"
+			#get the params list
+			args=$(parse_yaml "$l"|sed -n '/^Param: */{s///;p;q}')
+			[ -n "$args" ] && testinfo+=", Param: $args"
 
-                #get the condition config
-		condition=$(parse_yaml "$l"|sed -n '/^Condition: */{s///;p;q}')
-                [ -n "$condition" ] && testinfo+=", Condition: $condition"
+			#get the global config
+			conf=$(parse_yaml "$l"|sed -n '/^GlobalSetup: */{s///;p;q}')
+			sconf=$(eval set -- $conf; for ((i=1;i<=$#;i++)); do echo "${!i}"; done|sort)
+			sconf=$(echo "$sconf"| while read c; do echo -n "$c"|sed -e "s;';'\"'\"';g" -e "s/^/'/" -e "s/$/' /"; done)
+			[ -n "$sconf" ] && testinfo+=", GlobalSetup: $sconf"
 
-                [ "$FORMAT" = pol ] && {
-                    testinfo="fs-qe case:$name"
-                    [ -n "$args" ] && testinfo="$testinfo param:${args// /,}"
-                    testinfo="$testinfo tag:$pkgName,$level,$type"
-                    [ -n "$sconf" ] && { sconf=${sconf//\'/}; testinfo="$testinfo gset:${sconf// /,}"; }
-                }
-                echo "$testinfo"
-            done <<<"$subtests"
-        fi
+			[ "$FORMAT" = pol ] && {
+				testinfo="fs-qe case:$name"
+				[ -n "$args" ] && testinfo="$testinfo param:${args// /,}"
+				testinfo="$testinfo tag:$pkgName,$level,$type"
+				[ -n "$sconf" ] && { sconf=${sconf//\'/}; testinfo="$testinfo gset:${sconf// /,}"; }
+			}
+			echo "$testinfo"
+		done <<<"$subtests"
+	fi
 
-    popd >/dev/null
+	popd >/dev/null
 }
+
 _casesInfo() {
-    [ $# -lt 1 ] && {
-        echo "Usage: func <case_path [case_path...]>" >&2
-        return 1
-    }
-    for p in "$@"; do _caseInfo "$p"; done
+	[ $# -lt 1 ] && {
+		echo "Usage: func <case_path [case_path...]>" >&2
+		return 1
+	}
+	for p in "$@"; do _caseInfo "$p"; done
 }
+
 _getTestList() {
-    local paths= info=
+	local paths= info=
 
-    paths=$(find "$@" -name runtest.sh|sed -e 's;^.//*;;' -e 's;/runtest.sh$;;' -e 's/^runtest.sh$/./')
-    for d in $paths; do
-        [ -f ${d}/Makefile ] || continue
+	paths=$(find "$@" -name runtest.sh|sed -e 's;^.//*;;' -e 's;/runtest.sh$;;' -e 's/^runtest.sh$/./')
+	for d in $paths; do
+		[ -f ${d}/Makefile ] || continue
 
-        info=$(_caseInfo ${d})
-        [ -z "$info" ] && continue
+		info=$(_caseInfo ${d})
+		[ -z "$info" ] && continue
 
-        if [ "$EXP" = yes -o -n "$distro" ]; then
-            echo "$info" | expand_testlist $CONFF -d "$distro"
-        else
-            echo "$info"
-        fi
-    done
+		if [ "$EXP" = yes ]; then
+			echo "$info" | expand_testlist $CONFF -d "$distro"
+		else
+			echo "$info"
+		fi
+	done
 }
 
 # __main__
