utils: add brewkoji_install.sh
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/utils/downloadBrewScratch b/utils/downloadBrewScratch
--- a/utils/downloadBrewScratch
+++ b/utils/downloadBrewScratch
@@ -1,4 +1,15 @@
 #!/bin/bash
+#author jiyin@redhat.com
+
+# install brew
+which brew &>/dev/null || {
+	which brewkoji_install.sh ||
+		wget -N -q https://raw.githubusercontent.com/tcler/bkr-client-improved/master/utils/brewkoji_install.sh
+	bash brewkoji_install.sh >/dev/null || {
+		echo "{WARN} install brewkoji failed" >&2
+		exit 1
+	}
+}
 
 run() {
 	local cmdline=$1
@@ -9,55 +20,6 @@ run() {
 	ret=$?
 
 	return $ret
-}
-
-installBrew2() {
-	#https://mojo.redhat.com/docs/DOC-1024827
-	urls="
-	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-6-server.repo
-	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-6-client.repo
-	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-6-workstation.repo
-	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-7-server.repo
-	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-7-client.repo
-	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-7-workstation.repo
-	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-8-baseos.repo
-	curl -L -O http://download.devel.redhat.com/rel-eng/internal/rcm-tools-fedora.repo
-	"
-
-	local name=$(lsb_release -sir|awk '{print $1}')
-	local verx=$(lsb_release -sr|awk -F. '{print $1}')
-
-	pushd /etc/yum.repos.d
-	case $name in
-	RedHatEnterprise*)
-		case $verx in
-		6|7)
-			for type in server client workstation; do
-				curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-${verx}-${type}.repo
-				yum install -y koji brewkoji && break || rm rcm-tools-*.repo
-			done
-			;;
-		8)
-			curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-8-baseos.repo
-			yum install -y koji brewkoji python3-koji python3-pycurl || rm rcm-tools-*.repo
-			;;
-		esac
-		;;
-	Fedora*)
-		curl -L -O http://download.devel.redhat.com/rel-eng/internal/rcm-tools-fedora.repo
-		yum install -y koji brewkoji
-		;;
-	esac
-	popd
-
-	which brew &>/dev/null
-}
-installBrewFromSourceCode() {
-	git -c http.sslVerify=false clone  https://code.engineering.redhat.com/gerrit/rcm-brewkoji.git
-	cd rcm-brewkoji
-	make install >/dev/null
-
-	which brew &>/dev/null
 }
 
 Usage() {
@@ -85,15 +47,6 @@ storepath=$2
 	Usage
 	exit 1
 }
-
-# fix ssl certificate verify failed
-#curl https://password.corp.redhat.com/RH-IT-Root-CA.crt -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
-#curl https://password.corp.redhat.com/legacy.crt -o /etc/pki/ca-trust/source/anchors/legacy.crt
-#update-ca-trust
-
-# install koji & brew
-yum --setopt=strict=0 install -y koji python-koji python-pycurl brewkoji
-which brew &>/dev/null || installBrew2 || installBrewFromSourceCode
 
 # Download packges
 [ -d "$storepath" ] || {
