ns: add options: --ostree --bind --robind --volatile
[root@test ~]# ./ns
Usage:
  ./ns <-n nsname> [options] [exec -- cmdline | ps | del | install pkgs]
  ./ns ls

Options:
  -h, --help           ; show this help info
  -n {nsname}          ; ns(name space) name
  -p {pkgs}            ; packages you want in ns(name space)
  --veth-ip {ip1,ip2}  ; ip address pair for veth pair
  --macvlan-ip {ip1[,ip2...]} ; ip address[es] for ns macvlan if[s]
  --ostree={yes|no}    ; default is yes, use host os tree instead creating full seperated os tree
  --bind {src[:dst]}   ; see systemd-nspawn --bind
  --robind {src[:dst]} ; see systemd-nspawn --bind-ro
  --vol, --volatile {yes|no}  ; see systemd-nspawn --volatile. default is yes

Examples create ns by using host fs tree(/usr,/etc,/var):
  ./ns -n nfsc --veth-ip 192.168.2.1,192.168.2.2 --macvlan-ip 192.168.254.22,192.168.253.22 # create ns as nfs client

Examples create ns by using own fs tree(need option: --ostree=no -p "$pkg_list"):
  ./ns -n nfsserv --ostree=no -p "nfs-utils iproute" --veth-ip 192.168.1.1,192.168.1.2 --macvlan-ip 192.168.254.11,192.168.253.11 # create ns as nfs server

Examples sub-command:
  ./ns -n nfsc exec -- ls -l /               # exec command in ns
  ./ns -n nfsc exec ip addr show             # exec command in ns
  ./ns -n nfsc exec mkdir /mnt/nfs           # exec command in ns
  ./ns -n nfsc exec mount 192.168.2.1:/ /mnt/nfs    # exec command in ns
  ./ns -n nfsc exec mount 192.168.254.1:/ /mnt/nfs  # exec command in ns
  ./ns -n nfsc ps  # show ps tree of ns
  ./ns -n nfsc del # delete/remove ns
  ./ns -n nfsc install cifs-utils # install cifs-utils in ns
  ./ns ls          # list all ns

Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/utils/ns b/utils/ns
--- a/utils/ns
+++ b/utils/ns
@@ -4,8 +4,7 @@
 # dependency: systemd-nspawn
 # used to create light container/ns for nfs/cifs test on RHEL/CentOS 7 or later
 
-NSHome=~/NS
-NSHome=/var/lib/machines
+NSHome=/opt/NS
 
 [[ $(id -u) != 0 ]] && {
 	echo -e "{Warn} $0 need root permission, try:\n  sudo $0 ..." >&2
@@ -13,7 +12,7 @@ NSHome=/var/lib/machines
 }
 
 which screen &>/dev/null || dep=screen
-which tmux &>/dev/null || dep=\ tmux
+which tmux &>/dev/null || dep+=\ tmux
 which systemd-nspawn &>/dev/null || dep+=\ systemd-container
 [[ -n "$dep" ]] && {
 	echo -e "{Info} install dependences ..."
@@ -27,15 +26,23 @@ Usage() {
 	  $0 ls
 
 	Options:
-	  -h, --help          ; show this help info
-	  -n {nsname}         ; ns(name space) name
-	  -p {pkgs}           ; packages you want in ns(name space)
-	  --veth-ip {ip1,ip2} ; ip address pair for veth pair
+	  -h, --help           ; show this help info
+	  -n {nsname}          ; ns(name space) name
+	  -p {pkgs}            ; packages you want in ns(name space)
+	  --veth-ip {ip1,ip2}  ; ip address pair for veth pair
 	  --macvlan-ip {ip1[,ip2...]} ; ip address[es] for ns macvlan if[s]
+	  --ostree={yes|no}    ; default is yes, use host os tree instead creating full seperated os tree
+	  --bind {src[:dst]}   ; see systemd-nspawn --bind
+	  --robind {src[:dst]} ; see systemd-nspawn --bind-ro
+	  --vol, --volatile {yes|no}  ; see systemd-nspawn --volatile. default is yes
 
-	Examples:
-	  $0 -n nfsserv -p "nfs-utils iproute" --veth-ip 192.168.1.1,192.168.1.2 --macvlan-ip 192.168.254.11 # create ns as nfs server
-	  $0 -n nfsc -p "nfs-utils iproute" --veth-ip 192.168.2.1,192.168.2.2 --macvlan-ip 192.168.254.21 # create ns as nfs client
+	Examples create ns by using host fs tree(/usr,/etc,/var):
+	  $0 -n nfsc --veth-ip 192.168.2.1,192.168.2.2 --macvlan-ip 192.168.254.22,192.168.253.22 # create ns as nfs client
+
+	Examples create ns by using own fs tree(need option: --ostree=no -p "\$pkg_list"):
+	  $0 -n nfsserv --ostree=no -p "nfs-utils iproute" --veth-ip 192.168.1.1,192.168.1.2 --macvlan-ip 192.168.254.11,192.168.253.11 # create ns as nfs server
+
+	Examples sub-command:
 	  $0 -n nfsc exec -- ls -l /               # exec command in ns
 	  $0 -n nfsc exec ip addr show             # exec command in ns
 	  $0 -n nfsc exec mkdir /mnt/nfs           # exec command in ns
@@ -43,9 +50,9 @@ Usage() {
 	  $0 -n nfsc exec mount 192.168.254.1:/ /mnt/nfs  # exec command in ns
 	  $0 -n nfsc ps  # show ps tree of ns
 	  $0 -n nfsc del # delete/remove ns
+	  $0 -n nfsc install cifs-utils # install cifs-utils in ns
 	  $0 ls          # list all ns
 
-	  $0 -n nfsc install cifs-utils # install cifs-utils in ns
 	EOF
 }
 
@@ -66,14 +73,14 @@ ns_init_pid() {
 	local nsdir=$1
 	local ppid initpid
 
-	ppid=$(pgrep -f "^systemd-nspawn.*$nsdir$") || return 1
+	ppid=$(pgrep -f "^systemd-nspawn .*$nsdir$") || return 1
 	initpid=$(pgrep -f ^/usr/lib/systemd/systemd -P "$ppid") || return 1
 	echo $initpid
 }
 
 ns_pstree() {
 	local nsdir=$NSHome/$1
-	local tree=$(ps axf | sed -rn -e 's/^(( *[^ ]+){4} )(.*)$/\3 \t\t\t \1/' -e "/^( ._ )?systemd-nspawn -n.*${nsdir//\//\\/}/,/^( ._ )?[^ ]/p" | sed \$d)
+	local tree=$(ps axf | sed -rn -e 's/^(( *[^ ]+){4} )(.*)$/\3 # \1/' -e "/^( ._ )?systemd-nspawn .*${nsdir//\//\\/}/,/^( ._ )?[^ ]/p" | sed '/^[^ ]/d')
 	[[ "$tree" = ' \_ '* ]] && {
 		tree=$(sed 's/^....//' <<<"$tree")
 	}
@@ -97,11 +104,25 @@ getDefaultNic() {
 	ip route | awk '/default/{match($0,"dev ([^ ]+)",M); print M[1]; exit}'
 }
 
+OSTREE=yes
+VOLATILE=yes
+NET_MACVLAN_OPTS=
+BIND_OPTS=
+NS_VETH_IP=
+NS_MACVLAN_IPS=
+HOST_VETH_IP=
+InitPid=
+PKGS="nfs-utils cifs-utils autofs"
+
 # command line parse
 _at=`getopt -o hn:p: \
 	--long help \
 	--long veth-ip: \
 	--long macvlan-ip: \
+	--long ostree: \
+	--long bind: \
+	--long robind: \
+	--long volatile: --long vol: \
     -a -n "$0" -- "$@"`
 eval set -- "$_at"
 while true; do
@@ -111,6 +132,10 @@ while true; do
 	-p) PKGS="$2"; shift 2;;
 	--veth-ip) read HOST_VETH_IP NS_VETH_IP <<<"${2//,/ }"; shift 2;;
 	--macvlan-ip) NS_MACVLAN_IPS="${2//,/ }"; shift 2;;
+	--ostree) OSTREE=$2; shift 2;;
+	--bind) BIND_OPTS+="--bind=$2 "; shift 2;;
+	--robind) BIND_OPTS+="--bind-ro=$2 "; shift 2;;
+	--volatile|--vol) VOLATILE=$2; shift 2;;
 	--) shift; break;;
 	esac
 done
@@ -138,9 +163,11 @@ del*|del|de|d) shift
 	[[ -z "$NS" ]] && { Usage >&2; exit 1; }
 	systemd-run -M $NS "poweroff"
 	ns_pstree $NS | awk 'NF > 4 {print $(NF-3)}' | xargs kill 2>/dev/null
+	sleep 1
+	ns_pstree $NS | awk 'NF > 4 {print $(NF-3)}' | xargs kill -9 2>/dev/null
 	ip link del ve-$NS 2>/dev/null
-	macvlan4ns=$NS
-	for dev in $(ip a s | awk -F'[: @]+' -v pre=$macvlan4ns '/^[0-9]+:/ {if ($2 ~ "^" pre "[0-9]*$") print $2}'); do
+	macvlan4ns=${NS}
+	for dev in $(ip a s | awk -F'[: @]+' -v pre=${macvlan4ns} '/^[0-9]+:/ {if ($2 ~ "^" pre "[0-9]*$") print $2}'); do
 		ip link del "$dev" 2>/dev/null
 	done
 	exit $?;;
@@ -154,30 +181,12 @@ esac
 [[ -z "$NS" ]] && { Usage >&2; exit 1; }
 
 #remove existed one
-$0 del "$NS"
+$0 del "$NS" 2>/dev/null
 
-NS_VETH_IP=${NS_VETH_IP}
-NS_MACVLAN_IPS=${NS_MACVLAN_IPS}
-HOST_VETH_IP=${HOST_VETH_IP}
-macvlan4host=macvlan-host
-macvlan4ns=$NS
 NSdir=$NSHome/$NS
-InitPid=
-PKGS=${PKGS:-iputils iproute nfs-utils}
-
-echo -e "\n{INFO} creating NS directory $NSdir ..."
-mkdir -p $NSdir/etc
-\cp -rf /etc/yum.repos.d $NSdir/etc/.
-yum -y --nogpg --installroot=$NSdir install iputils $PKGS
-yum -y --nogpg --installroot=$NSdir clean all 2>/dev/null
-\cp /etc/{passwd,group,shadow} $NSdir/etc/.
-rm -rf $NSdir/var/cache/yum/*
-
-hostvethif=ve-$NS
-ip link del $hostvethif 2>/dev/null
 
 echo -e "\n{INFO} creating macvlan if for NS ..."
-NET_MACVLAN_OPTS=
+macvlan4ns=${NS}
 loop=0
 for addr in $NS_MACVLAN_IPS; do
 	is_valid_ip "$addr" || { echo -e "\n{WARN} '$addr' is not a valid address"|grep --color=always . >&2; continue; }
@@ -186,11 +195,25 @@ for addr in $NS_MACVLAN_IPS; do
 	NET_MACVLAN_OPTS+="--network-macvlan=$ifname "
 done
 
+echo -e "\n{INFO} creating fs tree for NS $NSdir ..."
+mkdir -p $NSdir
+if [[ "$OSTREE" = yes ]]; then
+	trap 'echo -e "\n{Note} can not abort now"' 1 2 15
+	mount / $NSdir/ -oro,bind
+	BIND_OPTS="--bind=/etc --bind=/var"
+else
+	yum -y --nogpg --installroot=$NSdir install systemd iproute iputils $PKGS
+	\cp -rf /etc/yum.repos.d $NSdir/etc/.
+	\cp /etc/{passwd,group,shadow} $NSdir/etc/.
+	yum -y --nogpg --installroot=$NSdir clean all 2>/dev/null
+	rm -rf $NSdir/var/cache/yum/*
+fi
+
 echo -e "\n{INFO} creating NS $NS ..."
 if which screen &>/dev/null; then
-	screen -dm -S $NS systemd-nspawn -n $NET_MACVLAN_OPTS -bD $NSdir
+	screen -dm -S $NS -- systemd-nspawn $BIND_OPTS --volatile=$VOLATILE -n $NET_MACVLAN_OPTS -bD $NSdir
 else
-	tmux new -s $NS -d "systemd-nspawn -n $NET_MACVLAN_OPTS -bD $NSdir"
+	tmux new -s $NS -d "systemd-nspawn $BIND_OPTS --volatile=$VOLATILE -n $NET_MACVLAN_OPTS -bD $NSdir"
 fi
 
 echo -e "\n{INFO} waiting NS $NSdir start ..."
@@ -198,13 +221,22 @@ sleep 1
 for ((i=0; i<8; i++)); do InitPid=$(ns_init_pid $NSdir) && break; sleep 1; done
 [[ -z "$InitPid" ]] && {
 	echo -e "\n{Error} something is wrong, exit ."
+	[[ "$OSTREE" = yes ]] && { umount $NSdir; }
+	$0 del "$NS" 2>/dev/null
 	exit 1
 }
 
 echo -e "\n{INFO} NS info"
 machinectl -l
 ns_pstree $NSdir
+[[ "$OSTREE" = yes ]] && {
+	umount $NSdir
+	trap - 1 2 15
+}
 
+# post setup
+macvlan4host=macvlan-host
+hostvethif=ve-$NS
 is_valid_ip $HOST_VETH_IP || { HOST_VETH_IP=; echo -e "\n{WARN} '$HOST_VETH_IP' is not a valid address"|grep --color=always . >&2; }
 is_valid_ip $NS_VETH_IP || { NS_VETH_IP=; echo -e "\n{WARN} '$NS_VETH_IP' is not a valid address"|grep --color=always . >&2; }
 if [[ -n "$HOST_VETH_IP" && -n "$NS_VETH_IP" ]]; then
@@ -242,7 +274,7 @@ for addr in $NS_MACVLAN_IPS; do
 done
 
 HOST_MACVLAN_IP=192.168.254.1
-echo -e "\n{INFO} setup macvlan host side $macvlan4host $HOST_MACVLAN_IP"
+echo -e "\n{INFO} setup default macvlan host side $macvlan4host $HOST_MACVLAN_IP"
 ip link show $macvlan4host &>/dev/null ||
 	ip link add link $(getDefaultNic) name $macvlan4host type macvlan mode bridge
 ip addr add $HOST_MACVLAN_IP/24 dev $macvlan4host
@@ -257,6 +289,7 @@ ip a s $macvlan4host
 loop=0
 for addr in $NS_MACVLAN_IPS; do
 	is_valid_ip "$addr" || { echo -e "\n{WARN} '$addr' is not a valid address"|grep --color=always . >&2; continue; }
+	[[ $addr = ${HOST_MACVLAN_IP%.*}.* ]] || continue
 	nsifname=mv-${macvlan4ns}$((loop++))
 	echo -e "\n{INFO} ping macvlan nic $addr ($macvlan4host -> $nsifname)"
 	while ! ping -c 2 $addr; do sleep 1; done
