utils/vershow: improve get urls by using 'bkr distro-trees-list'
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/utils/vershow b/utils/vershow
--- a/utils/vershow
+++ b/utils/vershow
@@ -23,35 +23,11 @@ done
 	exit 1
 }
 
-baseUrl="http://download.devel.redhat.com/"
-baseUrl="http://download.eng.bos.redhat.com/"
-distro_rel_eng() {
-	curl -k -L -u: ${baseUrl}rel-eng/  2>/dev/null |
-		awk -F'[<>]' '/"(latest-)?RHEL[-0-9.]+/&&/alt=".DIR."/{print "rel-eng/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
-	# change to be like http://download.eng.bos.redhat.com/rhel-x/rel-eng/RHEL-x/
-	curl -k -L -u: ${baseUrl}rhel-7/rel-eng/RHEL-7/  2>/dev/null |
-		awk -F'[<>]' '/"(latest-)?RHEL[-0-9.]+/&&/alt=".DIR."/{print "rhel-7/rel-eng/RHEL-7/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
-	curl -k -L -u: ${baseUrl}rhel-8/rel-eng/RHEL-8/  2>/dev/null |
-		awk -F'[<>]' '/"(latest-)?RHEL[-0-9.]+/&&/alt=".DIR."/{print "rhel-8/rel-eng/RHEL-8/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
-}
-distro_nightly() {
-	curl -k -L -u: ${baseUrl}nightly/  2>/dev/null |
-		awk -F'[<>]' '/"(latest-)?(RHEL|Pegas)[-0-9.]+/&&/alt=".DIR."/{print "nightly/" $5}' |sed 's;/$;;'|egrep -v -i '(Supplementary|DSRV-)';
-	# change to be like http://download.eng.bos.redhat.com/rhel-x/nightly/RHEL-x/
-	curl -k -L -u: ${baseUrl}rhel-7/nightly/RHEL-7/  2>/dev/null |
-		awk -F'[<>]' '/"(latest-)?RHEL[-0-9.]+/&&/alt=".DIR."/{print "rhel-7/nightly/RHEL-7/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
-	curl -k -L -u: ${baseUrl}rhel-8/nightly/RHEL-8/  2>/dev/null |
-		awk -F'[<>]' '/"(latest-)?RHEL[-0-9.]+/&&/alt=".DIR."/{print "rhel-8/nightly/RHEL-8/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
-}
-distro_released() {
-	curl -k -L -u: ${baseUrl}released/RHEL-5-Server  2>/dev/null |
-		awk -F'[<>]' '/"U[-0-9.]+.*\//&&/alt=".DIR."/{print "released/RHEL-5-Server/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
-	curl -k -L -u: ${baseUrl}released/RHEL-6  2>/dev/null |
-		awk -F'[<>]' '/"[0-9]+\.[0-9.]+.*\//&&/alt=".DIR."/{print "released/RHEL-6/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
-	curl -k -L -u: ${baseUrl}released/RHEL-7  2>/dev/null |
-		awk -F'[<>]' '/"[0-9]+\.[0-9.]+.*\//&&/alt=".DIR."/{print "released/RHEL-7/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
-	curl -k -L -u: ${baseUrl}released/RHEL-8  2>/dev/null |
-		awk -F'[<>]' '/"[0-9]+\.[0-9.]+.*\//&&/alt=".DIR."/{print "released/RHEL-8/" $5}' |sed 's;/$;;'|egrep -v -i Supplementary;
+lockf=/tmp/distroDB.w.lock
+trap "sigproc" SIGINT SIGTERM SIGHUP SIGQUIT
+sigproc() {
+	rm -f $lockf
+	exit
 }
 
 UpdateDB() {
@@ -60,55 +36,46 @@ UpdateDB() {
 
 	[ "$1" = YES ] && deepup=1
 	cd $dbRoot
+	rm -f .curl* #remove old version db files
 
 	rpm -q procmail >/dev/null || yum install -y procmail &>/dev/null
 	lockfile /tmp/distroDB.w.lock || return 0
 	#Update distro list
-	>distro.list.tmp
-	distro_rel_eng   >>distro.list.tmp
-	distro_nightly   >>distro.list.tmp
-	distro_released  >>distro.list.tmp
+	for family in 8 7 6 5; do
+		distro-list.sh -f $family -t all
+	done >distro.list.tmp
 	if [ ! -f distro.list ]; then
 		touch distro.list
 	fi
+
 	diff -pNu distro.list distro.list.tmp >distro.list.diff
 	\cp distro.list.tmp distro.list
 	sed -n '/^+[^+]/{s/^+//; p}' distro.list.diff >distro.list.up
 	[ -n "$deepup" ] && \cp distro.list distro.list.up
 
 	#Update pkg list
-	compose=compose/
-	while read distro _nil; do
+	while read distro; do
 		arch=$ARCH
-		[[ "$distro" =~ RHEL-(PPC64)?LE ]] && arch=ppc64le
-		rpath=Server/${arch}/os/Packages/
-		rhel5rpath=tree-${arch}/
+		urls=$(bkr distro-trees-list --limit=1 --name "$distro" --arch=${arch:-x86_64} | grep http:// | awk '{print $3 "Packages"}')
+		cachefile=.Curl.${distro// /_}.${arch}.cache
 
-		cachefile=.curl.${distro//\//:}.${arch}.cache
 		[[ -f $cachefile && ! $cachefile =~ latest ]] && continue
 
-		_rpath=$rhel5rpath$(echo $distro|egrep -o 'Server|Client') || {
-			_rpath=$compose$rpath
-		}
+		for url in $urls; do
+			if curl -sf -k -L -u: $url >$cachefile.tmp; then
+				[[ $distro = RHEL-8* ]] && {
+					curl -sf -k -L -u: ${url/BaseOS/AppStream} >>$cachefile.tmp  2>/dev/null
+				}
+				break
+			else
+				echo "[warn] get pkgs of '$distro' fail: $url" >&2
+			fi
+		done
 
-		[[ "$distro" = *RHEL-8* ]] && {
-			_rpath=compose/BaseOS/$arch/os/Packages/
-		}
-		echo "$distro"|grep -q released/ && _rpath=$rpath
-		echo "$distro"|grep -q released/RHEL-5 && _rpath=$arch/os/Server/
-
-		curl -k -L -u: ${baseUrl}${distro}/${_rpath}  >$cachefile.tmp  2>/dev/null
-		grep -q 'was not found on this server' $cachefile.tmp && {
-			curl -k -L -u: ${baseUrl}${distro}/${compose}${rpath}  >$cachefile.tmp  2>/dev/null
-		}
-		grep -q 'was not found on this server' $cachefile.tmp && {
-			c=$(echo $distro|sed -r -e 's/^.*\/(latest-)?RHEL-?//' -e 's/-.*$//')
-			curl -k -L -u: ${baseUrl}${distro}/${c}/${rpath}  >$cachefile.tmp  2>/dev/null
-		}
-
-		if grep -q 'kernel-' $cachefile.tmp; then
-			echo "# {${baseUrl}$(sed -r -n 's;^[ \t]*<title>Index of /(.*)</title>;\1;p' $cachefile.tmp)}" >$cachefile
-			awk -F'[<>]' '/alt=/{printf("%s\n", $5)}' $cachefile.tmp >>$cachefile
+		if grep -q 'kernel-' $cachefile.tmp; then  #fixme
+			echo "# {$url}" >$cachefile
+			sed -nr '/^.*href="([^"]+).rpm".*$/{s//\1/; p}' $cachefile.tmp >>$cachefile
+			#awk -F'[<>]' '/alt=/{printf("%s\n", $5)}' $cachefile.tmp >>$cachefile
 			# enable other user can modify these cachefile
 			chmod a+w $cachefile 2>/dev/null
 		fi
@@ -143,17 +110,17 @@ cd $dbRoot
 # do search
 pkgPart=${1}
 mydistro=${2}
-list=$(egrep -i -- "$mydistro" distro.list)
-while read distro _nil; do
-	cachefile=.curl.${distro//\//:}.${ARCH}.cache
-	[[ "$distro" =~ RHEL-LE ]] && cachefile=.curl.${distro//\//:}.ppc64le.cache
+mylist=$(egrep -i -- "$mydistro" distro.list)
+while read distro; do
+	cachefile=.Curl.${distro// /_}.${ARCH}.cache
 	[ -f $cachefile ] || continue
+
 	result=$(egrep -- "$pkgPart" $cachefile)
 	[ $? = 0 ] && {
 		[[ -z "$nocolor" ]] && echo -e "=> \033[1;34m$distro\033[0m" || echo -n "$distro -> "
 		echo "$result"
 	}
-done <<<"$list"
+done <<<"$mylist"
 
 if ! egrep -q "/usr/local/bin/vershow" /etc/crontab; then
 	if [ `id -u` = 0 ]; then
